"""initial schema

Revision ID: 664940028c51
Revises: 
Create Date: 2026-08-12 06:33:18.320782
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '664940028c51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realised_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealised_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_exposure', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_snapshots_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshots_trading_mode'), ['trading_mode'], unique=False)

    op.create_table('decisions',
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('intent_source', sa.String(length=64), nullable=True),
    sa.Column('intent_strategy', sa.String(length=64), nullable=True),
    sa.Column('risk_approved', sa.Boolean(), nullable=False),
    sa.Column('risk_rejection_reason', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_instrument'), ['instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_intent_source'), ['intent_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_intent_strategy'), ['intent_strategy'], unique=False)
        batch_op.create_index('ix_decisions_mode_ts', ['trading_mode', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_risk_approved'), ['risk_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_risk_rejection_reason'), ['risk_rejection_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_trading_mode'), ['trading_mode'], unique=False)

    op.create_table('orders',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_instrument'), ['instrument'], unique=False)
        batch_op.create_index('ix_orders_mode_created', ['trading_mode', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trading_mode'), ['trading_mode'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_instrument'), ['instrument'], unique=False)
        batch_op.create_index('ix_positions_instrument_mode', ['instrument', 'trading_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trading_mode'), ['trading_mode'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_trading_mode'), ['trading_mode'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_versions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_versions_trading_mode'), ['trading_mode'], unique=False)

    op.create_table('fills',
    sa.Column('fill_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('fill_id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_filled_at'), ['filled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_trading_mode'), ['trading_mode'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_trading_mode'))
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))
        batch_op.drop_index(batch_op.f('ix_fills_filled_at'))

    op.drop_table('fills')
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_versions_trading_mode'))
        batch_op.drop_index(batch_op.f('ix_strategy_versions_name'))

    op.drop_table('strategy_versions')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_trading_mode'))
        batch_op.drop_index(batch_op.f('ix_risk_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_risk_events_event_type'))

    op.drop_table('risk_events')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_trading_mode'))
        batch_op.drop_index('ix_positions_instrument_mode')
        batch_op.drop_index(batch_op.f('ix_positions_instrument'))

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_trading_mode'))
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_state'))
        batch_op.drop_index('ix_orders_mode_created')
        batch_op.drop_index(batch_op.f('ix_orders_instrument'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_trading_mode'))
        batch_op.drop_index(batch_op.f('ix_decisions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_decisions_risk_rejection_reason'))
        batch_op.drop_index(batch_op.f('ix_decisions_risk_approved'))
        batch_op.drop_index(batch_op.f('ix_decisions_outcome'))
        batch_op.drop_index(batch_op.f('ix_decisions_order_id'))
        batch_op.drop_index('ix_decisions_mode_ts')
        batch_op.drop_index(batch_op.f('ix_decisions_intent_strategy'))
        batch_op.drop_index(batch_op.f('ix_decisions_intent_source'))
        batch_op.drop_index(batch_op.f('ix_decisions_instrument'))

    op.drop_table('decisions')
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_snapshots_trading_mode'))
        batch_op.drop_index(batch_op.f('ix_account_snapshots_timestamp'))

    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
